# Generated by Django 2.2.3 on 2020-04-17 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tlog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tstatus', models.CharField(choices=[('Not Sent', 'Not Sent'), ('Pending', 'Pending'), ('Accesed', 'Accesed')], default='Not Sent', max_length=30)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('Access_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('astatus', models.CharField(choices=[('Not Sent', 'Not Sent'), ('Pending', 'Pending'), ('Accesed', 'Accesed')], default='Not sent', max_length=30)),
                ('s_key', models.CharField(blank=True, default='a', max_length=20)),
                ('dnld', models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', max_length=5)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlog_app.Files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
